POST http://localhost:5000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST http://localhost:5000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

GET http://localhost:5000/user/tweets/feed/

###
GET http://localhost:5000/user/following/

###
GET http://localhost:5000/user/followers/

###
GET http://localhost:5000/tweets/1/

###
GET http://loclhost:5000/tweets/1/likes/

###
GET http://localhost:5000/tweets/1/replies/

###
GET http://localhost:5000/user/tweets/

###
POST http://localhost:5000/user/tweets/
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

###

DELETE http://localhost:5000/tweets/1/
